general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: [sq_load_ball]
    parallels:
      priority_level_2: [pl_dejam]
      priority_level_1: [pl_protect, pl_intake_floor, pl_intake_wall, pl_shoot, pl_protect, pl_load_ball_into_elevator, pl_collect_balls]
    ss_drivetrain:
      priority_level_1: [st_drivetrain_zero, st_drivetrain_velocity]
      default: [st_drivetrain_percent]
    ss_collector:
      priority_level_1: [st_collector_zero, st_collector_intake_floor, st_collector_intake_wall, st_collector_retract, st_collector_eject]
      default: [st_collector_extend]
    ss_hopper:
      priority_level_1: [st_hopper_zero, st_hopper_load_elevator, st_hopper_collect, st_hopper_home, st_hopper_shoot]
      default: [st_hopper_stop]
    ss_elevator:
      priority_level_1: [st_elevator_zero, st_elevator_load_ball, st_elevator_prime, st_elevator_shoot]
      default: [st_elevator_stop]
    ss_flywheel:
      priority_level_1: [st_flywheel_zero, st_flywheel_prime, st_flywheel_shoot, st_flywheel_shoot_limelight, st_flywheel_stop]
      default: [st_flywheel_coast]
    ss_turret:
      priority_level_1: [st_turret_zero, st_turret_left, st_turret_right, st_turret_limelight]
      default: [st_turret_center]


  subsystems: [ss_drivetrain, ss_collector, ss_hopper, ss_elevator, ss_flywheel, ss_turret]

  input_booleans: [ipb_driver_left_trigger, ipb_driver_right_bumper,
                   ipb_operator_left_trigger, ipb_operator_left_bumper, ipb_operator_right_trigger, ipb_operator_right_bumper, ipb_operator_dpad_up, ipb_operator_dpad_right,
                   ipb_elevator_ball_sensor]

  input_numerics: [ipn_driver_left_y, ipn_driver_right_x]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right, opn_collector_rollers, opn_hopper, opn_elevator]

  output_booleans: [opb_collector_extended, opb_hopper_kicker_extended]


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_all:
  zero_timeout: 500

global_drivetrain:
  y_control: ipn_driver_left_y
  x_control: ipn_driver_right_x
  gearshift_control: ipb_driver_left_trigger
  velocity_mode_control: ipb_driver_right_bumper
  velocity_scalar_feetpersecond: 12.0

global_collector:

global_hopper:

global_elevator:

global_flywheel:
  macro_adjust: ipn_operator_left_y
  micro_adjust: ipn_operator_left_x
  macro_scalar: 10
  micro_scalar: 1

global_turret:
  macro_adjust: ipn_operator_right_y
  micro_adjust: ipn_operator_right_x
  macro_scalar: 10
  micro_scalar: 1




log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

