general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: []
    parallels:
      priority_level_2: [pl_dejam]
      priority_level_1: [pl_protect, pl_intake_floor, pl_intake_wall, pl_shoot, pl_protect]
    ss_drivetrain:
      priority_level_1: [st_drivetrain_zero, st_drivetrain_velocity]
      default: [st_drivetrain_percent]
    ss_collector:
      priority_level_1: [st_collector_zero, st_collector_intake_floor, st_collector_intake_wall, st_collector_retract, st_collector_eject]
      default: [st_collector_extend]

  subsystems: [ss_drivetrain, ss_collector]

  input_booleans: [ipb_driver_left_trigger, ipb_driver_right_bumper,
                   ipb_operator_left_trigger, ipb_operator_left_bumper, ipb_operator_right_trigger, ipb_operator_right_bumper, ipb_operator_dpad_up, ipb_operator_dpad_right]

  input_numerics: [ipn_driver_left_y, ipn_driver_right_x]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right]

  output_booleans: []


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_all:
  zero_timeout: 500

global_drivetrain:
  y_control: ipn_driver_left_y
  x_control: ipn_driver_right_x
  gearshift_control: ipb_driver_left_trigger
  velocity_mode_control: ipb_driver_right_bumper
  velocity_scalar_feetpersecond: 12.0

global_collector:




log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

